name: memlearn
description: A new Flutter project.

# Prevent accidental publishing to pub.dev.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  flutter_bloc: ^8.1.3
  flutter_dotenv: ^5.1.0
  flutter_screenutil: ^5.9.0
  solana: ^0.30.0
  solana_mobile_client: ^0.1.1
  supabase_flutter: ^1.10.19
  walletconnect_flutter_v2: ^2.1.4
  webcrypto: ^0.5.3
  welltested: ^2.1.3
  neopop: ^1.0.2
  cached_network_image: ^3.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  mockito: ^5.4.2

flutter:
  uses-material-design: true

  # Enable generation of localized Strings from arb files.
  generate: true

  assets:
    # Add assets from the images directory to the application.
    - assets/images/
    - .env
